//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Заказы
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class УчётЗаказовEntities : DbContext
    {
        public УчётЗаказовEntities()
            : base("name=УчётЗаказовEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Заказы> Заказы { get; set; }
        public virtual DbSet<ПостоянныеПокупатели> ПостоянныеПокупатели { get; set; }
        public virtual DbSet<Учётные_данные> Учётные_данные { get; set; }
    }
}
